# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92a3ea4f96263bb81799cae408bb08868fe1fc4f6c1aa8b3dd23f172bd16ead6c1c4ffb707efb0d8cbd37afba1e3bc1e883b433c48b49a2f32b35a4c713e336d

test:
  secret_key_base: 629491f51d7f3ae7413c7f55d590ac89203c5bf21626ebba81a1ffbefab60f4edc9b32cc86bbb859b6ccccc05633782e41832499ef27e6a41d532119e93de8f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
